#!/bin/bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins

chunkc core::hotload 1
chunkc core::log_file stdout

chunkc set 3_desktop_offset_right        180

chunkc set 4_desktop_offset_top          180
chunkc set 4_desktop_offset_bottom       180
chunkc set 4_desktop_offset_left         180
chunkc set 4_desktop_offset_right        180

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                1
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_region_locked          1

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#
# chunkc set mouse_modifier              \"cmd shift\"
chunkc set mouse_modifier                fn

#
# NOTE: these settings require chwm-sa.
#       (https://github.com/koekeishiya/chwm-sa)
#

# chunkc set window_float_topmost          0
# chunkc set window_fade_inactive          0
# chunkc set window_fade_alpha             0.85
# chunkc set window_fade_duration          0.25
# chunkc set window_use_cgs_move           0

#
# NOTE: the following are config variables for the chunkwm-border plugin.
#

chunkc set focused_border_color          0xff4a4a4a
chunkc set focused_border_width          10
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  1

#
# NOTE: specify plugins to load when chunkwm starts.
#       if chunkc plugin_dir is not set, the absolutepath is necessary.
#

#
# NOTE: shell commands require escaped quotes
#       to pass value containing a whitespace.
#

chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner \"Terminal\" --state float
chunkc tiling::rule --owner \"iTerm\" --state float
chunkc tiling::rule --owner \"Game\" --state float
chunkc tiling::rule --owner Stickies --state float

# if plugin_dir is set, it will search that directory.
# if plugin_dir is not set, absolute path is necessary.
chunkc core::load border.so
chunkc core::load tiling.so
chunkc core::load ffm.so
